import { getCurrentSubject, getCustomSubjects } from './storage.js';

const syllabusData = {
  'English': [
    { title: 'Chapter 1: Speed Reading Basics',
      body: '<p>Speed reading is the practice of reading text at a faster rate than average without losing comprehension...</p>' },
    { title: 'Chapter 2: Rhythm & Pacing',
      body: '<p>Every language has its own natural rhythm. English follows a stress-timed rhythm...</p>' },
    { title: 'Chapter 3: Intonation Patterns',
      body: '<p>Intonation refers to the rise and fall of pitch in speech...</p>' },
    { title: 'Chapter 4: Stress & Emphasis',
      body: '<p>When we speak, we naturally place stress on certain words and syllables...</p>' },
    { title: 'Chapter 5: Advanced Pronunciation',
      body: '<p>Advanced pronunciation focuses on connected speech features: elision, assimilation...</p>' },
    { title: 'Chapter 6: Sentence Patterns (Module)',
      body: '<p>Mastering sentence patterns is crucial for verbal aptitude. Common patterns include S+V+O+C...</p>' }
  ],
  'Python': [
    { title: 'Unit 1 — Chapter 1: Python Basics & Environment',
      body: '<p><strong>Source: Basics of Python Programming — Unit I</strong></p><p>Python is a high-level, interpreted, dynamically-typed language created by <strong>Guido van Rossum</strong> in 1991. It emphasizes readability and simplicity, making it ideal for beginners and professionals alike.</p><h4>🔹 Key Features</h4><ul><li>Simple, readable syntax — code reads like English</li><li>Interpreted — no compilation needed</li><li>Dynamically typed — variables need no type declaration</li><li>Platform-independent — runs on Windows, Linux, Mac</li><li>Extensive standard library and third-party packages</li></ul><h4>🔹 Python Applications</h4><ul><li>Web Development (Django, Flask)</li><li>Data Science & ML (NumPy, Pandas, TensorFlow)</li><li>Automation & Scripting</li><li>Game Development (Pygame)</li></ul><h4>🔹 Getting Started</h4><pre><code># Your first Python program\nprint("Hello, World!")\nprint("Welcome to VaaniAI Python Course")</code></pre><ul><li>Install Python from python.org</li><li>Use <code>python --version</code> to verify installation</li><li>Python IDLE vs VS Code vs Jupyter Notebook</li><li>Python 2 vs Python 3 — always use Python 3</li><li>Running scripts: <code>python filename.py</code></li></ul>' },

    { title: 'Unit 1 — Chapter 2: Variables, Data Types & Operators',
      body: '<p><strong>Source: Basics of Python Programming — Unit I</strong></p><p>Variables store data values. Python is <strong>dynamically typed</strong> — the type is determined at runtime.</p><h4>🔹 Data Types</h4><ul><li><strong>int</strong> — integers: <code>x = 10</code></li><li><strong>float</strong> — decimals: <code>pi = 3.14</code></li><li><strong>str</strong> — text: <code>name = "Python"</code></li><li><strong>bool</strong> — <code>True</code> or <code>False</code></li><li><strong>complex</strong> — <code>z = 3 + 4j</code></li><li><strong>NoneType</strong> — <code>x = None</code></li></ul><h4>🔹 Type Conversion</h4><pre><code>x = int("42")      # str → int\ny = float(10)      # int → float\nz = str(3.14)      # float → str\nprint(type(x))     # &lt;class \'int\'&gt;</code></pre><h4>🔹 Operators</h4><ul><li><strong>Arithmetic:</strong> <code>+  -  *  /  //  %  **</code></li><li><strong>Comparison:</strong> <code>==  !=  &gt;  &lt;  &gt;=  &lt;=</code></li><li><strong>Logical:</strong> <code>and  or  not</code></li><li><strong>Assignment:</strong> <code>=  +=  -=  *=  /=</code></li><li><strong>Identity:</strong> <code>is</code>, <code>is not</code></li><li><strong>Membership:</strong> <code>in</code>, <code>not in</code></li></ul><h4>🔹 Input & Output</h4><pre><code>name = input("Enter your name: ")\nage = int(input("Enter age: "))\nprint(f"Hello {name}, you are {age} years old")</code></pre>' },

    { title: 'Unit 2 — Chapter 3: Control Flow Statements',
      body: '<p><strong>Source: Basics of Python Programming — Unit II</strong></p><p>Control flow determines the order in which statements execute. Python uses <strong>indentation</strong> to define code blocks (no braces!).</p><h4>🔹 if / elif / else</h4><pre><code>marks = 75\nif marks >= 90:\n    print("Grade: O")\nelif marks >= 75:\n    print("Grade: A")\nelif marks >= 60:\n    print("Grade: B")\nelse:\n    print("Grade: C")</code></pre><h4>🔹 Nested if</h4><pre><code>num = 15\nif num > 0:\n    if num % 2 == 0:\n        print("Positive Even")\n    else:\n        print("Positive Odd")</code></pre><h4>🔹 Ternary / Conditional Expression</h4><pre><code>result = "Pass" if marks >= 35 else "Fail"\nprint(result)</code></pre><h4>🔹 match-case (Python 3.10+)</h4><pre><code>day = "Monday"\nmatch day:\n    case "Monday": print("Start of week")\n    case "Friday": print("End of week")\n    case _: print("Midweek")</code></pre>' },

    { title: 'Unit 2 — Chapter 4: Loops & Iteration',
      body: '<p><strong>Source: Basics of Python Programming — Unit II</strong></p><p>Loops execute a block of code repeatedly. Python has two loop types: <code>for</code> and <code>while</code>.</p><h4>🔹 for Loop</h4><pre><code># Loop over a range\nfor i in range(1, 6):\n    print(i)\n\n# Loop over a list\nfruits = ["apple", "banana", "mango"]\nfor fruit in fruits:\n    print(fruit)</code></pre><h4>🔹 while Loop</h4><pre><code>count = 1\nwhile count <= 5:\n    print(f"Count: {count}")\n    count += 1</code></pre><h4>🔹 Loop Control</h4><ul><li><code>break</code> — exits the loop immediately</li><li><code>continue</code> — skips current iteration</li><li><code>pass</code> — placeholder, does nothing</li></ul><pre><code>for i in range(10):\n    if i == 5: break\n    if i % 2 == 0: continue\n    print(i)  # prints 1, 3</code></pre><h4>🔹 Nested Loops & else Clause</h4><pre><code>for i in range(1, 4):\n    for j in range(1, 4):\n        print(i * j, end=" ")\n    print()\n\n# for-else\nfor n in range(2, 10):\n    if n % 2 == 0:\n        break\nelse:\n    print("No even number found")</code></pre><h4>🔹 List Comprehension</h4><pre><code>squares = [x**2 for x in range(10)]\nevens = [x for x in range(20) if x % 2 == 0]</code></pre>' },

    { title: 'Unit 3 — Chapter 5: Functions & Modules',
      body: '<p><strong>Source: Basics of Python Programming — Unit III</strong></p><p>Functions are reusable blocks of code that perform a specific task. They promote <strong>DRY (Don\'t Repeat Yourself)</strong> programming.</p><h4>🔹 Defining & Calling Functions</h4><pre><code>def greet(name):\n    """Greets a person by name"""\n    return f"Hello, {name}!"\n\nprint(greet("Shandosh"))  # Hello, Shandosh!</code></pre><h4>🔹 Function Arguments</h4><ul><li><strong>Positional:</strong> <code>add(3, 5)</code></li><li><strong>Keyword:</strong> <code>greet(name="AI")</code></li><li><strong>Default:</strong> <code>def greet(name="User")</code></li><li><strong>*args:</strong> variable positional args → tuple</li><li><strong>**kwargs:</strong> variable keyword args → dict</li></ul><pre><code>def total(*args):\n    return sum(args)\nprint(total(1, 2, 3, 4))  # 10\n\ndef show(**kwargs):\n    for k, v in kwargs.items():\n        print(f"{k} = {v}")\nshow(name="Python", version=3)</code></pre><h4>🔹 Lambda Functions</h4><pre><code>square = lambda x: x ** 2\nadd = lambda a, b: a + b\nprint(square(5))  # 25</code></pre><h4>🔹 Scope — LEGB Rule</h4><ul><li><strong>L</strong>ocal → <strong>E</strong>nclosing → <strong>G</strong>lobal → <strong>B</strong>uilt-in</li><li><code>global</code> keyword to modify global variable inside function</li><li><code>nonlocal</code> keyword for nested function scope</li></ul><h4>🔹 Modules & Import</h4><pre><code>import math\nprint(math.sqrt(16))    # 4.0\nprint(math.pi)          # 3.14159\n\nfrom random import randint\nprint(randint(1, 100))\n\nimport os\nprint(os.getcwd())</code></pre>' },

    { title: 'Unit 3 — Chapter 6: Strings & String Methods',
      body: '<p><strong>Source: Basics of Python Programming — Unit III</strong></p><p>Strings are sequences of characters enclosed in single, double, or triple quotes. They are <strong>immutable</strong> in Python.</p><h4>🔹 String Creation</h4><pre><code>s1 = "Hello"\ns2 = \'World\'\ns3 = """Multi\nline string"""\ns4 = r"Raw \n string"   # raw string</code></pre><h4>🔹 String Operations</h4><pre><code>s = "Python"\nprint(len(s))        # 6\nprint(s[0])          # P\nprint(s[-1])         # n\nprint(s[1:4])        # yth  (slicing)\nprint(s * 2)         # PythonPython\nprint(s + " Rocks")  # Python Rocks</code></pre><h4>🔹 String Methods</h4><ul><li><code>upper()</code>, <code>lower()</code>, <code>title()</code></li><li><code>strip()</code>, <code>lstrip()</code>, <code>rstrip()</code></li><li><code>split(sep)</code>, <code>join(iterable)</code></li><li><code>replace(old, new)</code></li><li><code>find(sub)</code>, <code>count(sub)</code></li><li><code>startswith()</code>, <code>endswith()</code></li><li><code>isdigit()</code>, <code>isalpha()</code>, <code>isalnum()</code></li></ul><h4>🔹 String Formatting</h4><pre><code>name = "VaaniAI"\nmarks = 95.5\nprint(f"Name: {name}, Marks: {marks:.2f}")\nprint("Name: %s, Marks: %.2f" % (name, marks))\nprint("Name: {}, Marks: {}".format(name, marks))</code></pre>' },

    { title: 'Unit 4 — Chapter 7: Lists & Tuples',
      body: '<p><strong>Source: Basics of Python Programming — Unit IV</strong></p><p>Lists and Tuples are sequence data structures. Lists are <strong>mutable</strong>; Tuples are <strong>immutable</strong>.</p><h4>🔹 Lists</h4><pre><code>fruits = ["apple", "banana", "mango"]\nfruits.append("grape")     # add to end\nfruits.insert(1, "kiwi")   # add at index\nfruits.remove("banana")    # remove by value\nfruits.pop()               # remove last\nfruits.sort()              # sort ascending\nfruits.reverse()           # reverse order\nprint(len(fruits))         # length</code></pre><h4>🔹 List Slicing</h4><pre><code>nums = [0, 1, 2, 3, 4, 5]\nprint(nums[1:4])    # [1, 2, 3]\nprint(nums[::-1])   # [5, 4, 3, 2, 1] reversed\nprint(nums[::2])    # [0, 2, 4] every 2nd</code></pre><h4>🔹 List Comprehension</h4><pre><code>squares = [x**2 for x in range(1, 6)]\n# [1, 4, 9, 16, 25]\n\neven_squares = [x**2 for x in range(10) if x % 2 == 0]</code></pre><h4>🔹 Tuples</h4><pre><code>point = (3, 4)\nx, y = point            # tuple unpacking\nprint(point[0])         # 3\nprint(point.count(3))   # 1\nprint(point.index(4))   # 1\n\n# Single element tuple\nsingle = (42,)          # comma is required!</code></pre><h4>🔹 Nested Structures</h4><pre><code>matrix = [[1,2,3],[4,5,6],[7,8,9]]\nprint(matrix[1][2])  # 6</code></pre>' },

    { title: 'Unit 4 — Chapter 8: Dictionaries & Sets',
      body: '<p><strong>Source: Basics of Python Programming — Unit IV</strong></p><p>Dictionaries store key-value pairs. Sets store unique, unordered elements.</p><h4>🔹 Dictionaries</h4><pre><code>student = {\n    "name": "Shandosh",\n    "age": 20,\n    "marks": 95\n}\n\n# Access\nprint(student["name"])          # Shandosh\nprint(student.get("age", 0))    # 20\n\n# Modify\nstudent["marks"] = 98\nstudent["course"] = "Python"\n\n# Delete\ndel student["age"]\nstudent.pop("course")</code></pre><h4>🔹 Dictionary Methods</h4><ul><li><code>keys()</code> — all keys</li><li><code>values()</code> — all values</li><li><code>items()</code> — key-value pairs</li><li><code>update(dict)</code> — merge dictionaries</li><li><code>clear()</code> — empty the dict</li></ul><pre><code>for key, value in student.items():\n    print(f"{key}: {value}")</code></pre><h4>🔹 Sets</h4><pre><code>s1 = {1, 2, 3, 4}\ns2 = {3, 4, 5, 6}\n\nprint(s1 | s2)   # Union: {1,2,3,4,5,6}\nprint(s1 & s2)   # Intersection: {3,4}\nprint(s1 - s2)   # Difference: {1,2}\nprint(s1 ^ s2)   # Symmetric diff: {1,2,5,6}\n\ns1.add(10)\ns1.remove(1)\nprint(len(s1))</code></pre><h4>🔹 Dictionary Comprehension</h4><pre><code>squares = {x: x**2 for x in range(1, 6)}\n# {1:1, 2:4, 3:9, 4:16, 5:25}</code></pre>' },

    { title: 'Unit 5 — Chapter 9: OOP — Classes & Inheritance',
      body: '<p><strong>Source: Basics of Python Programming — Unit V</strong></p><p>Object-Oriented Programming organizes code using <strong>classes</strong> (blueprints) and <strong>objects</strong> (instances).</p><h4>🔹 Defining a Class</h4><pre><code>class Student:\n    # Class variable\n    school = "VaaniAI Academy"\n\n    def __init__(self, name, marks):\n        # Instance variables\n        self.name = name\n        self.marks = marks\n\n    def display(self):\n        print(f"Name: {self.name}, Marks: {self.marks}")\n\n    def grade(self):\n        if self.marks >= 90: return "O"\n        elif self.marks >= 75: return "A"\n        else: return "B"\n\n# Create objects\ns1 = Student("Shandosh", 95)\ns1.display()            # Name: Shandosh, Marks: 95\nprint(s1.grade())       # O</code></pre><h4>🔹 Inheritance</h4><pre><code>class Person:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return f"Hi, I am {self.name}"\n\nclass Teacher(Person):\n    def __init__(self, name, subject):\n        super().__init__(name)\n        self.subject = subject\n    def speak(self):\n        return f"I teach {self.subject}"\n\nt = Teacher("Dr. Lakshmi", "Python")\nprint(t.speak())  # I teach Python</code></pre><h4>🔹 Encapsulation</h4><pre><code>class BankAccount:\n    def __init__(self, balance):\n        self.__balance = balance  # private\n    def deposit(self, amount):\n        self.__balance += amount\n    def get_balance(self):\n        return self.__balance</code></pre><h4>🔹 Special / Dunder Methods</h4><ul><li><code>__init__</code> — constructor</li><li><code>__str__</code> — string representation</li><li><code>__len__</code> — length</li><li><code>__add__</code> — operator overloading</li></ul>' },

    { title: 'Unit 5 — Chapter 10: Exception Handling & File I/O',
      body: '<p><strong>Source: Basics of Python Programming — Unit V</strong></p><p>Exception handling makes programs robust by gracefully managing runtime errors. File I/O allows reading and writing data to files.</p><h4>🔹 Exception Handling</h4><pre><code>try:\n    num = int(input("Enter number: "))\n    result = 100 / num\n    print(f"Result: {result}")\nexcept ValueError:\n    print("Invalid input — not a number!")\nexcept ZeroDivisionError:\n    print("Cannot divide by zero!")\nexcept Exception as e:\n    print(f"Unexpected error: {e}")\nelse:\n    print("No errors occurred")\nfinally:\n    print("Execution complete")</code></pre><h4>🔹 Raising Exceptions</h4><pre><code>def check_age(age):\n    if age < 0:\n        raise ValueError("Age cannot be negative")\n    return age\n\ntry:\n    check_age(-5)\nexcept ValueError as e:\n    print(e)</code></pre><h4>🔹 Custom Exceptions</h4><pre><code>class InvalidMarksError(Exception):\n    pass\n\ndef validate(marks):\n    if marks > 100:\n        raise InvalidMarksError("Marks exceed 100")</code></pre><h4>🔹 File I/O</h4><pre><code># Write to file\nwith open("notes.txt", "w") as f:\n    f.write("Python is awesome\\n")\n    f.writelines(["Line 2\\n", "Line 3\\n"])\n\n# Read from file\nwith open("notes.txt", "r") as f:\n    content = f.read()\n    print(content)\n\n# Read line by line\nwith open("notes.txt") as f:\n    for line in f:\n        print(line.strip())</code></pre><ul><li>File modes: <code>"r"</code> read, <code>"w"</code> write, <code>"a"</code> append, <code>"rb"</code> binary</li><li><code>with</code> statement auto-closes the file</li><li><code>os.path.exists()</code> to check if file exists</li></ul>' }
  ],
  'Java': [
    { title: 'Ch 1: Getting Started with Java',
      body: '<p><strong>Source: Java Notes for Professionals — GoalKicker.com (Ch 1, 5, 14)</strong></p><p>Java is a class-based, object-oriented, platform-independent language. Philosophy: <strong>Write Once, Run Anywhere (WORA)</strong> via the JVM.</p><h4>🔹 How Java Works</h4><ul><li>Write <code>.java</code> source file → <code>javac</code> compiles to <code>.class</code> bytecode → JVM runs it</li><li><strong>JDK</strong> = Java Development Kit (compile + run)</li><li><strong>JRE</strong> = Java Runtime Environment (run only)</li><li><strong>JVM</strong> = Java Virtual Machine (executes bytecode)</li></ul><h4>🔹 Your First Program</h4><pre><code>public class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n        System.out.println("Welcome to Java!");\n    }\n}</code></pre><ul><li>Compile: <code>javac HelloWorld.java</code></li><li>Run: <code>java HelloWorld</code></li><li>Every Java file must have a class matching the filename</li><li><code>main()</code> is the entry point — always <code>public static void</code></li></ul><h4>🔹 Primitive Data Types (Ch 14)</h4><ul><li><code>int</code> — 32-bit integer: <code>int age = 25;</code></li><li><code>long</code> — 64-bit integer: <code>long pop = 7_900_000_000L;</code></li><li><code>double</code> — 64-bit decimal: <code>double pi = 3.14159;</code></li><li><code>char</code> — single character: <code>char grade = \'A\';</code></li><li><code>boolean</code> — true/false: <code>boolean passed = true;</code></li><li><code>byte</code>, <code>short</code>, <code>float</code> — smaller/less-precise variants</li></ul>' },

    { title: 'Ch 2: Operators, Control Flow & Strings',
      body: '<p><strong>Source: Java Notes for Professionals — GoalKicker.com (Ch 9, 13, 15)</strong></p><h4>🔹 Operators (Ch 13)</h4><ul><li><strong>Arithmetic:</strong> <code>+  -  *  /  %</code></li><li><strong>Comparison:</strong> <code>==  !=  &gt;  &lt;  &gt;=  &lt;=</code></li><li><strong>Logical:</strong> <code>&amp;&amp;  ||  !</code></li><li><strong>Assignment:</strong> <code>=  +=  -=  *=  /=</code></li><li><strong>Ternary:</strong> <code>int max = (a &gt; b) ? a : b;</code></li></ul><h4>🔹 Control Flow (Ch 9)</h4><pre><code>int score = 85;\nif (score >= 90) {\n    System.out.println("A Grade");\n} else if (score >= 75) {\n    System.out.println("B Grade");\n} else {\n    System.out.println("C Grade");\n}\n\n// Switch statement\nswitch (score / 10) {\n    case 10:\n    case 9: System.out.println("A"); break;\n    case 8: System.out.println("B"); break;\n    default: System.out.println("C");\n}</code></pre><h4>🔹 Strings (Ch 15)</h4><pre><code>String name = "Java Notes";\nSystem.out.println(name.length());        // 10\nSystem.out.println(name.toUpperCase());   // JAVA NOTES\nSystem.out.println(name.substring(0, 4)); // Java\nSystem.out.println(name.contains("Notes")); // true\nSystem.out.println(name.replace("Notes", "Pro")); // Java Pro\n\n// String comparison — ALWAYS use .equals(), not ==\nString a = "hello";\nString b = "hello";\nSystem.out.println(a.equals(b));    // true\nSystem.out.println(a.equalsIgnoreCase("HELLO")); // true</code></pre>' },

    { title: 'Ch 3: Arrays & Loops',
      body: '<p><strong>Source: Java Notes for Professionals — GoalKicker.com (Ch 9, 20)</strong></p><h4>🔹 Arrays (Ch 20)</h4><pre><code>// Declare and initialise\nint[] scores = {85, 92, 78, 95, 88};\nString[] names = new String[5];\n\n// Access\nSystem.out.println(scores[0]);  // 85\nSystem.out.println(scores.length); // 5\n\n// Modify\nscores[2] = 100;\n\n// 2D Array\nint[][] matrix = {{1,2,3},{4,5,6},{7,8,9}};\nSystem.out.println(matrix[1][2]); // 6</code></pre><h4>🔹 Loops (Ch 9)</h4><pre><code>// for loop\nfor (int i = 0; i < scores.length; i++) {\n    System.out.println(scores[i]);\n}\n\n// enhanced for-each\nfor (int s : scores) {\n    System.out.println(s);\n}\n\n// while loop\nint i = 0;\nwhile (i < 5) {\n    System.out.println(i);\n    i++;\n}\n\n// do-while\ndo {\n    System.out.print("Runs at least once");\n} while (false);</code></pre><h4>🔹 Arrays Utility Class</h4><pre><code>import java.util.Arrays;\nArrays.sort(scores);          // sort ascending\nArrays.fill(scores, 0);       // fill with 0\nint[] copy = Arrays.copyOf(scores, 3); // copy first 3\nSystem.out.println(Arrays.toString(scores)); // [0, 0, 0, 0, 0]</code></pre>' },

    { title: 'Ch 4: Object-Oriented Programming',
      body: '<p><strong>Source: Java Notes for Professionals — GoalKicker.com (Ch 3, 24, 25, 28)</strong></p><p>OOP is the backbone of Java. Everything (except primitives) is an object.</p><h4>🔹 Classes & Objects (Ch 25)</h4><pre><code>public class Student {\n    // Fields\n    private String name;\n    private int marks;\n\n    // Constructor\n    public Student(String name, int marks) {\n        this.name = name;\n        this.marks = marks;\n    }\n\n    // Getters & Setters (Ch 3)\n    public String getName() { return name; }\n    public void setMarks(int m) { marks = m; }\n\n    // Method\n    public String grade() {\n        if (marks >= 90) return "O";\n        else if (marks >= 75) return "A";\n        return "B";\n    }\n\n    @Override\n    public String toString() {\n        return name + " [" + marks + "]";\n    }\n}\n\n// Create objects\nStudent s1 = new Student("Shandosh", 95);\nSystem.out.println(s1.getName()); // Shandosh\nSystem.out.println(s1.grade());   // O\nSystem.out.println(s1);           // Shandosh [95]</code></pre><h4>🔹 Inheritance (Ch 28)</h4><pre><code>class Person {\n    String name;\n    Person(String n) { name = n; }\n    void speak() { System.out.println("Hi, I am " + name); }\n}\n\nclass Teacher extends Person {\n    String subject;\n    Teacher(String n, String s) {\n        super(n);       // call parent constructor\n        subject = s;\n    }\n    @Override\n    void speak() { System.out.println("I teach " + subject); }\n}\n\nTeacher t = new Teacher("Dr. Kumar", "Java");\nt.speak();  // I teach Java</code></pre>' },

    { title: 'Ch 5: Interfaces & Polymorphism',
      body: '<p><strong>Source: Java Notes for Professionals — GoalKicker.com (Ch 26, 29)</strong></p><h4>🔹 Interfaces (Ch 29)</h4><p>An interface defines a contract — a set of methods a class must implement.</p><pre><code>interface Shape {\n    double area();       // abstract method\n    default String type() { return "Shape"; }  // default method (Ch 26)\n}\n\nclass Circle implements Shape {\n    double r;\n    Circle(double r) { this.r = r; }\n\n    @Override\n    public double area() {\n        return Math.PI * r * r;\n    }\n}\n\nclass Rectangle implements Shape {\n    double w, h;\n    Rectangle(double w, double h) { this.w = w; this.h = h; }\n\n    @Override\n    public double area() { return w * h; }\n}\n\nShape c = new Circle(5);\nShape r = new Rectangle(4, 6);\nSystem.out.println(c.area());  // 78.54\nSystem.out.println(r.area());  // 24.0</code></pre><h4>🔹 Polymorphism</h4><ul><li><strong>Compile-time (overloading):</strong> same method name, different parameters</li><li><strong>Runtime (overriding):</strong> subclass provides its own implementation</li></ul><pre><code>// Method Overloading\nclass Calculator {\n    int add(int a, int b) { return a + b; }\n    double add(double a, double b) { return a + b; }\n    int add(int a, int b, int c) { return a + b + c; }\n}</code></pre>' },

    { title: 'Ch 6: Type Conversion & Reference Types',
      body: '<p><strong>Source: Java Notes for Professionals — GoalKicker.com (Ch 2, 4)</strong></p><h4>🔹 Type Conversion (Ch 2)</h4><pre><code>// Implicit (widening) — automatic, no data loss\nint i = 42;\nlong l = i;        // int → long OK\ndouble d = l;      // long → double OK\n\n// Explicit (narrowing) — manual cast required\ndouble pi = 3.14159;\nint truncated = (int) pi;   // 3 — decimal dropped!\n\n// String conversion\nString s = String.valueOf(42);    // int → String\nint n = Integer.parseInt("42");   // String → int\ndouble x = Double.parseDouble("3.14"); // String → double\n\n// Wrapper classes (autoboxing)\nInteger boxed = 42;       // auto-boxing: int → Integer\nint unboxed = boxed;      // auto-unboxing: Integer → int</code></pre><h4>🔹 Reference Data Types (Ch 4)</h4><ul><li>Objects, arrays, and Strings are reference types</li><li>A reference variable holds the <strong>memory address</strong> of the object, not the value itself</li></ul><pre><code>// == compares references, .equals() compares content\nString a = new String("hello");\nString b = new String("hello");\nSystem.out.println(a == b);        // false (different objects)\nSystem.out.println(a.equals(b));   // true  (same content)\n\n// null — a reference pointing to nothing\nString str = null;\nif (str != null) {\n    System.out.println(str.length());\n} // safe null check</code></pre>' },

    { title: 'Ch 7: Collections Framework',
      body: '<p><strong>Source: Java Notes for Professionals — GoalKicker.com (Ch 20+)</strong></p><p>The Java Collections Framework provides ready-made, generic data structures.</p><h4>🔹 ArrayList — Dynamic Array</h4><pre><code>import java.util.ArrayList;\nArrayList&lt;String&gt; list = new ArrayList&lt;&gt;();\nlist.add("Java");      // add to end\nlist.add("Python");\nlist.add(0, "C++");    // insert at index 0\nlist.remove("Python"); // remove by value\nlist.remove(0);        // remove by index\n\nSystem.out.println(list.get(0));   // Java\nSystem.out.println(list.size());   // 1\nSystem.out.println(list.contains("Java")); // true\n\nfor (String lang : list) {\n    System.out.println(lang);\n}</code></pre><h4>🔹 HashMap — Key-Value Store</h4><pre><code>import java.util.HashMap;\nHashMap&lt;String, Integer&gt; scores = new HashMap&lt;&gt;();\nscores.put("Alice", 95);\nscores.put("Bob", 88);\nscores.put("Charlie", 92);\n\nSystem.out.println(scores.get("Alice"));  // 95\nSystem.out.println(scores.containsKey("Bob")); // true\nscores.remove("Bob");\n\nfor (String name : scores.keySet()) {\n    System.out.println(name + ": " + scores.get(name));\n}</code></pre><h4>🔹 HashSet & LinkedList</h4><pre><code>// HashSet — unique elements, no order\nHashSet&lt;Integer&gt; set = new HashSet&lt;&gt;();\nset.add(1); set.add(2); set.add(1); // duplicate ignored\nSystem.out.println(set.size()); // 2\n\n// LinkedList — doubly linked, use as Queue\nLinkedList&lt;String&gt; queue = new LinkedList&lt;&gt;();\nqueue.offer("First");   // enqueue\nqueue.offer("Second");\nSystem.out.println(queue.poll()); // "First" — dequeue</code></pre>' },

    { title: 'Ch 8: Exception Handling',
      body: '<p><strong>Source: Java Notes for Professionals — GoalKicker.com (Exception chapters)</strong></p><p>Exception handling makes programs robust by gracefully managing runtime errors.</p><h4>🔹 try-catch-finally</h4><pre><code>public class Divider {\n    public static void main(String[] args) {\n        try {\n            int result = 10 / 0;             // ArithmeticException\n            System.out.println(result);\n        } catch (ArithmeticException e) {\n            System.out.println("Error: " + e.getMessage());\n        } catch (Exception e) {\n            System.out.println("Unexpected: " + e);\n        } finally {\n            System.out.println("Always executes");  // cleanup code\n        }\n    }\n}</code></pre><h4>🔹 Checked vs Unchecked</h4><ul><li><strong>Checked exceptions</strong> — must be handled at compile time: <code>IOException</code>, <code>SQLException</code></li><li><strong>Unchecked exceptions</strong> — runtime errors: <code>NullPointerException</code>, <code>ArrayIndexOutOfBoundsException</code></li></ul><h4>🔹 throw & throws</h4><pre><code>public int divide(int a, int b) throws ArithmeticException {\n    if (b == 0) throw new ArithmeticException("Cannot divide by zero");\n    return a / b;\n}</code></pre><h4>🔹 Custom Exception</h4><pre><code>class InvalidAgeException extends RuntimeException {\n    public InvalidAgeException(String msg) {\n        super(msg);\n    }\n}\n\nvoid validateAge(int age) {\n    if (age < 0) throw new InvalidAgeException("Age cannot be negative: " + age);\n}</code></pre><h4>🔹 Try-with-Resources</h4><pre><code>// AutoCloseable — file closes automatically\ntry (FileReader fr = new FileReader("file.txt");\n     BufferedReader br = new BufferedReader(fr)) {\n    String line;\n    while ((line = br.readLine()) != null) {\n        System.out.println(line);\n    }\n} catch (IOException e) {\n    e.printStackTrace();\n}</code></pre>' },

    { title: 'Ch 9: Generics & StringBuilder',
      body: '<p><strong>Source: Java Notes for Professionals — GoalKicker.com (Ch 16, Generics)</strong></p><h4>🔹 Generics</h4><p>Generics allow writing type-safe, reusable code without casting.</p><pre><code>// Generic method\npublic &lt;T extends Comparable&lt;T&gt;&gt; T findMax(T a, T b) {\n    return (a.compareTo(b) &gt;= 0) ? a : b;\n}\n\n// Works with any Comparable type\nSystem.out.println(findMax(10, 20));      // 20\nSystem.out.println(findMax("Java", "C")); // Java\n\n// Generic class\nclass Box&lt;T&gt; {\n    private T value;\n    Box(T v) { this.value = v; }\n    T get() { return value; }\n}\n\nBox&lt;Integer&gt; intBox = new Box&lt;&gt;(42);\nBox&lt;String&gt; strBox = new Box&lt;&gt;("Hello");\nSystem.out.println(intBox.get()); // 42</code></pre><h4>🔹 StringBuilder (Ch 16)</h4><p><code>String</code> is immutable — use <code>StringBuilder</code> for efficient string building in loops.</p><pre><code>StringBuilder sb = new StringBuilder();\nfor (int i = 1; i <= 5; i++) {\n    sb.append("Item ").append(i).append("\\n");\n}\nString result = sb.toString();\nSystem.out.println(result);\n\n// Common StringBuilder methods\nsb.insert(0, "START\\n");   // insert at position\nsb.delete(0, 6);           // delete range\nsb.reverse();              // reverse content\nsb.replace(0, 4, "JAVA");  // replace range\nSystem.out.println(sb.length()); // character count</code></pre>' },

    { title: 'Ch 10: Garbage Collection, Packages & javadoc',
      body: '<p><strong>Source: Java Notes for Professionals — GoalKicker.com (Ch 6, 7, 8, 27)</strong></p><h4>🔹 Garbage Collection (Ch 8)</h4><p>Java automatically manages memory — the <strong>Garbage Collector (GC)</strong> reclaims memory of objects no longer referenced.</p><ul><li>No manual <code>free()</code> or <code>delete</code> like C/C++</li><li>GC runs automatically in the background</li><li>An object is eligible for GC when no references point to it</li><li><code>System.gc()</code> — suggests GC (not guaranteed to run)</li></ul><pre><code>// After this, the String object "Old" is eligible for GC\nString s = "Old";\ns = "New";  // "Old" has no reference now → GC can collect it</code></pre><h4>🔹 Packages (Ch 27)</h4><pre><code>// Declare a package at top of file\npackage com.vaaniai.students;\n\n// Import specific class\nimport java.util.ArrayList;\n\n// Import all from package\nimport java.util.*;\n\n// Standard packages:\n// java.lang — String, Math, System (auto-imported)\n// java.util — Collections, Arrays, Scanner\n// java.io   — File, InputStream, Reader\n// java.net  — URL, Socket</code></pre><h4>🔹 javadoc (Ch 6)</h4><pre><code>/**\n * Calculates the area of a circle.\n *\n * @param radius the radius of the circle\n * @return the area as a double\n * @throws IllegalArgumentException if radius is negative\n */\npublic double circleArea(double radius) {\n    if (radius &lt; 0) throw new IllegalArgumentException("Negative radius");\n    return Math.PI * radius * radius;\n}</code></pre><h4>🔹 Command Line Arguments (Ch 7)</h4><pre><code>public class Greet {\n    public static void main(String[] args) {\n        if (args.length > 0) {\n            System.out.println("Hello, " + args[0]);\n        }\n    }\n}\n// Run: java Greet Shandosh → Hello, Shandosh</code></pre>' }
  ],
  'C++': [
    { title: 'Ch 1: Introduction to the Course',
      body: '<p><strong>Source: Introduction to Computers and Programming using C++ and MATLAB — Bielajew (U. of Michigan)</strong></p><p>This chapter introduces the fundamental concepts of computing, programming, and the C++ ecosystem you will use throughout the course.</p><h4>🔹 What is a Computer?</h4><ul><li>Hardware vs Software — CPU, RAM, Storage, I/O</li><li>How a computer executes instructions — fetch, decode, execute cycle</li><li>Binary representation — everything in a computer is 0s and 1s</li><li>Operating Systems — Windows, Linux, macOS</li></ul><h4>🔹 Why C++?</h4><ul><li>High performance — close to the hardware</li><li>Used in: game engines, embedded systems, operating systems, scientific computing</li><li>Compiled language — <code>g++ program.cpp -o program</code></li><li>Strongly typed — errors caught at compile time</li></ul><h4>🔹 Setting Up Your Environment</h4><pre><code>// Your first C++ program\n#include &lt;iostream&gt;\nusing namespace std;\n\nint main() {\n    cout &lt;&lt; "Hello, World!" &lt;&lt; endl;\n    return 0;\n}</code></pre><ul><li>Install GCC (Linux/Mac) or MinGW (Windows)</li><li>Compile: <code>g++ hello.cpp -o hello</code></li><li>Run: <code>./hello</code> or <code>hello.exe</code></li><li>IDE options: VS Code, Code::Blocks, CLion</li></ul>' },

    { title: 'Ch 2: Data Representations',
      body: '<p><strong>Source: Chapter 2 — Data Representations</strong></p><p>Before writing programs, you must understand how computers store and represent data internally using binary arithmetic.</p><h4>🔹 Binary Number System</h4><ul><li>Base-2: only digits 0 and 1</li><li>Convert decimal to binary: 13 = <strong>1101</strong></li><li>Convert binary to decimal: 1101 = 8+4+0+1 = <strong>13</strong></li><li>Hexadecimal: base-16, digits 0–9 and A–F</li></ul><h4>🔹 Integer Representation</h4><pre><code>int a = 42;        // 4 bytes = 32 bits\nshort b = 100;     // 2 bytes = 16 bits\nlong c = 1000000L; // 8 bytes = 64 bits\nunsigned int d = 255; // no negative values</code></pre><ul><li>Two\'s complement for negative integers</li><li>Overflow — what happens when you exceed the range</li><li>Signed vs Unsigned integers</li></ul><h4>🔹 Floating-Point Math</h4><pre><code>float  f = 3.14f;     // 4 bytes, ~7 decimal digits\ndouble d = 3.14159;   // 8 bytes, ~15 decimal digits\n\ncout &lt;&lt; fixed &lt;&lt; setprecision(4) &lt;&lt; d; // 3.1416</code></pre><ul><li>IEEE 754 standard for floating-point</li><li>Precision limitations — <code>0.1 + 0.2 ≠ 0.3</code> exactly</li><li>Use <code>double</code> for scientific computing</li></ul>' },

    { title: 'Ch 3: Algorithms & Pseudocode',
      body: '<p><strong>Source: Chapter 3 — Algorithms and Pseudocodes</strong></p><p>An algorithm is a step-by-step procedure to solve a problem. Pseudocode is a plain-language description of an algorithm before writing actual code.</p><h4>🔹 What is an Algorithm?</h4><ul><li>Well-defined set of instructions</li><li>Must be: <strong>finite</strong>, <strong>unambiguous</strong>, <strong>effective</strong></li><li>Examples: sorting, searching, calculating</li></ul><h4>🔹 Pseudocode Example — Find Max</h4><pre><code>BEGIN\n  INPUT a, b, c\n  IF a > b AND a > c THEN\n    OUTPUT "a is largest"\n  ELSE IF b > c THEN\n    OUTPUT "b is largest"\n  ELSE\n    OUTPUT "c is largest"\n  END IF\nEND</code></pre><h4>🔹 Sequencing, Branching, Looping</h4><ul><li><strong>Sequence:</strong> statements execute one after another</li><li><strong>Branching:</strong> if/else — choose a path based on condition</li><li><strong>Looping:</strong> repeat a block while a condition is true</li></ul><h4>🔹 Computer Architecture & Execution</h4><ul><li>CPU executes machine code instructions sequentially</li><li>Program Counter (PC) — tracks current instruction</li><li>Memory hierarchy: registers → cache → RAM → disk</li><li>Compiler translates C++ → machine code</li></ul>' },

    { title: 'Ch 4: Getting Started in C++',
      body: '<p><strong>Source: Chapter 4 — Getting Started in C++</strong></p><p>This chapter gets you writing and running real C++ programs — covering variables, input/output, and basic arithmetic.</p><h4>🔹 Program Structure</h4><pre><code>#include &lt;iostream&gt;\nusing namespace std;\n\nint main() {\n    // Your code goes here\n    return 0;  // 0 = success\n}</code></pre><h4>🔹 Variables & Data Types</h4><pre><code>int    age    = 20;       // integer\ndouble gpa    = 3.85;     // decimal\nchar   grade  = \'A\';      // single character\nbool   passed = true;     // boolean\nstring name   = "Shandosh"; // text (needs &lt;string&gt;)</code></pre><h4>🔹 Input & Output</h4><pre><code>#include &lt;iostream&gt;\nusing namespace std;\n\nint main() {\n    int age;\n    cout &lt;&lt; "Enter your age: ";\n    cin  &gt;&gt; age;\n    cout &lt;&lt; "You are " &lt;&lt; age &lt;&lt; " years old." &lt;&lt; endl;\n    return 0;\n}</code></pre><h4>🔹 Basic Arithmetic</h4><ul><li><code>+  -  *  /  %</code> — arithmetic operators</li><li>Integer division: <code>7 / 2 = 3</code> (truncates!)</li><li>Modulo: <code>7 % 2 = 1</code> (remainder)</li><li>Cast to double: <code>(double)7 / 2 = 3.5</code></li><li><code>pow(x, n)</code>, <code>sqrt(x)</code> from <code>&lt;cmath&gt;</code></li></ul>' },

    { title: 'Ch 5: Control Flow — Loops',
      body: '<p><strong>Source: Chapter 5 — Control Flow</strong></p><p>Control flow structures let you make decisions and repeat actions in your programs.</p><h4>🔹 if / else if / else</h4><pre><code>int score = 82;\nif (score >= 90) {\n    cout &lt;&lt; "Grade: A";\n} else if (score >= 75) {\n    cout &lt;&lt; "Grade: B";\n} else if (score >= 60) {\n    cout &lt;&lt; "Grade: C";\n} else {\n    cout &lt;&lt; "Grade: F";\n}</code></pre><h4>🔹 while Loop</h4><pre><code>int i = 1;\nwhile (i &lt;= 5) {\n    cout &lt;&lt; i &lt;&lt; " ";\n    i++;\n}\n// Output: 1 2 3 4 5</code></pre><h4>🔹 do-while Loop</h4><pre><code>int n;\ndo {\n    cout &lt;&lt; "Enter positive number: ";\n    cin &gt;&gt; n;\n} while (n &lt;= 0);  // always executes at least once</code></pre><h4>🔹 for Loop</h4><pre><code>for (int i = 0; i &lt; 5; i++) {\n    cout &lt;&lt; i * i &lt;&lt; " ";  // 0 1 4 9 16\n}\n\n// Nested for loop — multiplication table\nfor (int i = 1; i &lt;= 3; i++) {\n    for (int j = 1; j &lt;= 3; j++) {\n        cout &lt;&lt; i*j &lt;&lt; "\\t";\n    }\n    cout &lt;&lt; endl;\n}</code></pre><ul><li><code>break</code> — exit loop immediately</li><li><code>continue</code> — skip to next iteration</li></ul>' },

    { title: 'Ch 6: Functions & Abstraction',
      body: '<p><strong>Source: Chapter 6 — Early Abstraction: Functions</strong></p><p>Functions let you break programs into reusable, manageable pieces — a core principle of good software design.</p><h4>🔹 Why Functions?</h4><ul><li>Avoid code repetition (DRY — Don\'t Repeat Yourself)</li><li>Makes code easier to read and test</li><li>Each function does one specific job</li></ul><h4>🔹 Defining & Calling Functions</h4><pre><code>// Function declaration (prototype)\ndouble square(double x);\n\n// Function definition\ndouble square(double x) {\n    return x * x;\n}\n\nint main() {\n    cout &lt;&lt; square(5.0);  // Output: 25\n    return 0;\n}</code></pre><h4>🔹 Call by Value vs Call by Reference</h4><pre><code>// Call by VALUE — copy is passed, original unchanged\nvoid doubleVal(int x) { x = x * 2; }\n\n// Call by REFERENCE — original is modified\nvoid doubleRef(int &x) { x = x * 2; }\n\nint main() {\n    int a = 5;\n    doubleVal(a);  // a is still 5\n    doubleRef(a);  // a is now 10\n}</code></pre><h4>🔹 Scope</h4><ul><li><strong>Local scope:</strong> variable exists only inside its function</li><li><strong>Global scope:</strong> variable accessible everywhere (avoid when possible)</li><li>Use function parameters instead of globals</li></ul>' },

    { title: 'Ch 7: Chars, Strings & Data Abstraction',
      body: '<p><strong>Source: Chapter 7 — More Variable Types, Data Abstraction</strong></p><p>Beyond numbers, C++ handles characters and text. The <code>string</code> class provides powerful text manipulation tools.</p><h4>🔹 The char Type</h4><pre><code>char letter = \'A\';       // single character in single quotes\nchar newline = \'\\n\';    // escape characters\nchar tab = \'\\t\';\n\ncout &lt;&lt; (int)\'A\';  // 65 — ASCII value\ncout &lt;&lt; (char)65;  // A — ASCII to char</code></pre><h4>🔹 ASCII Table Highlights</h4><ul><li>\'A\'–\'Z\' = 65–90</li><li>\'a\'–\'z\' = 97–122</li><li>\'0\'–\'9\' = 48–57</li><li><code>toupper(c)</code>, <code>tolower(c)</code>, <code>isdigit(c)</code>, <code>isalpha(c)</code></li></ul><h4>🔹 The string Class</h4><pre><code>#include &lt;string&gt;\nstring name = "C++ Programming";\n\ncout &lt;&lt; name.length();          // 15\ncout &lt;&lt; name.substr(0, 3);      // C++\ncout &lt;&lt; name.find("Prog");      // 4\nname.replace(4, 11, "Mastery"); // C++ Mastery\n\n// Concatenation\nstring greeting = "Hello " + name;</code></pre><h4>🔹 String Input</h4><pre><code>string fullName;\ncout &lt;&lt; "Enter name: ";\ngetline(cin, fullName);  // reads entire line including spaces\ncout &lt;&lt; "Hello, " &lt;&lt; fullName;</code></pre>' },

    { title: 'Ch 8: Arrays, Structures & 2D Data',
      body: '<p><strong>Source: Chapter 8 — More Data Abstraction: Arrays and Structures</strong></p><p>Arrays store multiple values of the same type. Structures group different types together into a single unit.</p><h4>🔹 1D Arrays</h4><pre><code>int scores[5] = {85, 92, 78, 95, 88};\n\n// Access & modify\ncout &lt;&lt; scores[0];  // 85\nscores[2] = 100;    // modify index 2\n\n// Loop through array\nfor (int i = 0; i &lt; 5; i++) {\n    cout &lt;&lt; scores[i] &lt;&lt; " ";\n}</code></pre><h4>🔹 2D Arrays</h4><pre><code>int matrix[3][3] = {\n    {1, 2, 3},\n    {4, 5, 6},\n    {7, 8, 9}\n};\n\ncout &lt;&lt; matrix[1][2];  // 6\n\n// Nested loop to traverse\nfor (int r = 0; r &lt; 3; r++) {\n    for (int c = 0; c &lt; 3; c++) {\n        cout &lt;&lt; matrix[r][c] &lt;&lt; "\\t";\n    }\n    cout &lt;&lt; endl;\n}</code></pre><h4>🔹 C++ Structures</h4><pre><code>struct Student {\n    string name;\n    int age;\n    double gpa;\n};\n\nStudent s1 = {"Shandosh", 20, 3.9};\ncout &lt;&lt; s1.name &lt;&lt; " GPA: " &lt;&lt; s1.gpa;\n\n// Array of structs\nStudent class_[30];\nclass_[0] = {"Alice", 21, 3.7};</code></pre>' },

    { title: 'Ch 9: Pointers & Memory',
      body: '<p><strong>Source: Chapter 9 — Pointers</strong></p><p>Pointers are variables that store memory addresses. They are one of C++\'s most powerful (and tricky) features.</p><h4>🔹 Pointer Basics</h4><pre><code>int x = 42;\nint* ptr = &x;       // ptr holds the address of x\n\ncout &lt;&lt; x;           // 42  (value)\ncout &lt;&lt; &x;          // 0x7fff... (address)\ncout &lt;&lt; ptr;         // 0x7fff... (same address)\ncout &lt;&lt; *ptr;        // 42  (dereference — value at address)</code></pre><h4>🔹 Modifying via Pointer</h4><pre><code>*ptr = 100;          // changes x to 100\ncout &lt;&lt; x;           // 100</code></pre><h4>🔹 Pointers & Arrays</h4><pre><code>int arr[] = {10, 20, 30};\nint* p = arr;        // points to first element\n\ncout &lt;&lt; *p;          // 10\ncout &lt;&lt; *(p + 1);    // 20 — pointer arithmetic\ncout &lt;&lt; *(p + 2);    // 30</code></pre><h4>🔹 Call by Reference Using Pointers</h4><pre><code>void swap(int* a, int* b) {\n    int temp = *a;\n    *a = *b;\n    *b = temp;\n}\n\nint x = 5, y = 10;\nswap(&x, &y);  // x=10, y=5 after swap</code></pre><h4>🔹 Dynamic Memory</h4><pre><code>int* arr = new int[5];   // allocate on heap\narr[0] = 100;\ndelete[] arr;            // MUST free memory!</code></pre>' },

    { title: 'Ch 10: Applications & Numerical Methods',
      body: '<p><strong>Source: Chapter 10 — A Potpourri of Applications</strong></p><p>This chapter applies everything learned to real-world programming problems, including numerical methods used in engineering and science.</p><h4>🔹 Finding Zeros — Binary Chop (Bisection Method)</h4><p>Used to find the root of a function f(x) = 0, where the sign changes between two points.</p><pre><code>#include &lt;iostream&gt;\n#include &lt;cmath&gt;\nusing namespace std;\n\ndouble f(double x) { return x*x - 2; }  // find sqrt(2)\n\nint main() {\n    double lo = 0, hi = 2, mid;\n    for (int i = 0; i &lt; 50; i++) {\n        mid = (lo + hi) / 2;\n        if (f(lo) * f(mid) &lt; 0)\n            hi = mid;\n        else\n            lo = mid;\n    }\n    cout &lt;&lt; "sqrt(2) ≈ " &lt;&lt; mid;  // 1.41421356...\n    return 0;\n}</code></pre><h4>🔹 Other Practical Applications</h4><ul><li><strong>Sorting algorithms:</strong> Bubble Sort, Selection Sort, Insertion Sort</li><li><strong>Searching:</strong> Linear search, Binary search on sorted arrays</li><li><strong>Statistics:</strong> Mean, variance, standard deviation from arrays</li><li><strong>Prime numbers:</strong> Sieve of Eratosthenes</li></ul><pre><code>// Calculate mean & std deviation\ndouble mean = 0;\nfor (int i = 0; i &lt; n; i++) mean += data[i];\nmean /= n;\n\ndouble variance = 0;\nfor (int i = 0; i &lt; n; i++) variance += pow(data[i]-mean, 2);\nvariance /= n;\ndouble stddev = sqrt(variance);</code></pre>' },

    { title: 'Ch 11: Introduction to MATLAB',
      body: '<p><strong>Source: Chapter 11 — Programming in MATLAB</strong></p><p>MATLAB (Matrix Laboratory) is a high-level language designed for numerical computing, data analysis, and visualization. It complements C++ for scientific and engineering applications.</p><h4>🔹 Why MATLAB?</h4><ul><li>Built-in matrix operations — no loops needed for linear algebra</li><li>Excellent data visualization with <code>plot()</code>, <code>surf()</code>, <code>mesh()</code></li><li>Ideal for prototyping algorithms quickly</li><li>Widely used in engineering, finance, and research</li></ul><h4>🔹 MATLAB Basics</h4><pre><code>% This is a comment in MATLAB\nx = 5;                    % variable assignment\ny = x^2;                  % power\ndisp(y);                  % display: 25\n\n% Arrays (called vectors in MATLAB)\nv = [1, 2, 3, 4, 5];\ndisp(v * 2)               % [2, 4, 6, 8, 10]\n\n% Matrix\nA = [1 2; 3 4];           % 2x2 matrix\ndisp(det(A))              % determinant: -2</code></pre><h4>🔹 Loops & Conditionals</h4><pre><code>% for loop\nfor i = 1:5\n    disp(i^2)\nend\n\n% while loop\nn = 1;\nwhile n &lt; 10\n    n = n * 2;\nend\n\n% if/else\nif x > 0\n    disp(\'Positive\')\nelseif x == 0\n    disp(\'Zero\')\nelse\n    disp(\'Negative\')\nend</code></pre><h4>🔹 M-Files (Scripts & Functions)</h4><pre><code>% myFunc.m\nfunction result = myFunc(a, b)\n    result = a^2 + b^2;\nend\n\n% Call from command window:\nmyFunc(3, 4)   % returns 25</code></pre>' }
  ]
};

const modulesData = {
  'English': [
    { num: 'Module 1', title: 'Foundations of Reading', desc: 'Basic phonics, letter sounds, and simple words', status: 'Completed', progress: 100, icon: '✓', class: 'completed' },
    { num: 'Module 2', title: 'Sentence Formation', desc: 'Building simple and compound sentences', status: 'Completed', progress: 100, icon: '✓', class: 'completed' },
    { num: 'Module 3', title: 'Reading Fluency', desc: 'Speed reading, rhythm and intonation patterns', status: '65% Done', progress: 65, icon: '●', class: 'active-unit' },
    { num: 'Module 4', title: 'Verbal Aptitude', desc: 'Sentence patterns, voice, and grammar mastery', status: '0% Done', progress: 0, icon: '📖', class: '' }
  ],
  'Python': [
    { num: 'Unit 1', title: 'Python Basics & Environment', desc: 'Features, installation, variables, data types, operators, I/O', status: 'In Progress', progress: 30, icon: '●', class: 'active-unit' },
    { num: 'Unit 2', title: 'Control Flow & Loops', desc: 'if/elif/else, for, while, break, continue, comprehensions', status: '0% Done', progress: 0, icon: '📖', class: '' },
    { num: 'Unit 3', title: 'Functions, Strings & Modules', desc: 'def, lambda, *args/**kwargs, scope, string methods, import', status: 'Locked', progress: 0, icon: '🔒', class: 'locked' },
    { num: 'Unit 4', title: 'Data Structures', desc: 'Lists, Tuples, Dictionaries, Sets & comprehensions', status: 'Locked', progress: 0, icon: '🔒', class: 'locked' },
    { num: 'Unit 5', title: 'OOP, Exceptions & File I/O', desc: 'Classes, inheritance, try/except, file read/write', status: 'Locked', progress: 0, icon: '🔒', class: 'locked' }
  ],
  'Java': [
    { num: 'Group 1', title: 'Java Basics & Syntax', desc: 'Getting started, primitives, operators, control flow, strings (Ch 1–2)', status: 'In Progress', progress: 20, icon: '●', class: 'active-unit' },
    { num: 'Group 2', title: 'Arrays, Loops & OOP', desc: 'Arrays, loops, classes, objects, inheritance (Ch 3–4)', status: '0% Done', progress: 0, icon: '📖', class: '' },
    { num: 'Group 3', title: 'Interfaces & Type System', desc: 'Interfaces, polymorphism, type conversion, references (Ch 5–6)', status: 'Locked', progress: 0, icon: '🔒', class: 'locked' },
    { num: 'Group 4', title: 'Collections & Exceptions', desc: 'ArrayList, HashMap, HashSet, try-catch, custom exceptions (Ch 7–8)', status: 'Locked', progress: 0, icon: '🔒', class: 'locked' },
    { num: 'Group 5', title: 'Generics, GC & Packages', desc: 'Generics, StringBuilder, garbage collection, packages, javadoc (Ch 9–10)', status: 'Locked', progress: 0, icon: '🔒', class: 'locked' }
  ],
  'C++': [
    { num: 'Part 1', title: 'Foundations of Computing', desc: 'Intro, binary data, algorithms & pseudocode (Ch 1–3)', status: 'In Progress', progress: 20, icon: '●', class: 'active-unit' },
    { num: 'Part 2', title: 'Core C++ Programming', desc: 'Variables, I/O, control flow, loops, functions (Ch 4–6)', status: '0% Done', progress: 0, icon: '📖', class: '' },
    { num: 'Part 3', title: 'Data & Memory', desc: 'Chars, strings, arrays, structs, pointers (Ch 7–9)', status: 'Locked', progress: 0, icon: '🔒', class: 'locked' },
    { num: 'Part 4', title: 'Applications & MATLAB', desc: 'Numerical methods, sorting, algorithms, MATLAB intro (Ch 10–11)', status: 'Locked', progress: 0, icon: '🔒', class: 'locked' }
  ]
};

function normaliseSubject(raw) {
  if (!raw) return 'English';
  const map = { 'python': 'Python', 'java': 'Java', 'cpp': 'C++', 'c++': 'C++', 'english': 'English' };
  const lower = raw.toLowerCase();
  
  // If it's a standard hardcoded subject, return the mapped version
  if (map[lower]) return map[lower];

  // Otherwise, it's a custom subject, check if it exists in local storage
  const customSubjects = getCustomSubjects();
  const keys = Object.keys(customSubjects);
  const match = keys.find(k => k.toLowerCase() === lower);
  
  return match || raw;
}

function getChapters() {
  const subject = normaliseSubject(getCurrentSubject());
  const customSubjects = getCustomSubjects();
  
  if (customSubjects[subject] && customSubjects[subject].chapters) {
    return customSubjects[subject].chapters;
  }
  
  return syllabusData[subject] || syllabusData['English'];
}

function getModules() {
  const subject = normaliseSubject(getCurrentSubject());
  const customSubjects = getCustomSubjects();
  
  if (customSubjects[subject] && customSubjects[subject].modules) {
    return customSubjects[subject].modules;
  }
  
  return modulesData[subject] || modulesData['English'];
}

let currentIdx = 0;

export function loadChapter(idx) {
  const chapters = getChapters();
  currentIdx = idx;
  
  // Re-render sidebar list if needed
  const sidebar = document.querySelector('.chapter-list');
  if (sidebar && sidebar.children.length !== chapters.length) {
    refreshSyllabusUI();
  }

  document.querySelectorAll('.chapter-item').forEach((c, i) => {
    c.className = 'chapter-item' + (i < idx ? ' done' : i === idx ? ' active-ch' : '');
  });
  
  if (chapters[idx]) {
    const titleEl = document.getElementById('chapterTitle');
    const bodyEl = document.getElementById('chapterBody');
    if (titleEl) titleEl.textContent = chapters[idx].title;
    if (bodyEl) bodyEl.innerHTML    = chapters[idx].body;
    
    const fill = document.querySelector('.mini-fill');
    const span = document.querySelector('.content-progress span');
    if (fill) fill.style.width = `${Math.round(((idx + 1) / chapters.length) * 100)}%`;
    if (span) span.textContent = `${idx + 1} of ${chapters.length}`;

    localStorage.setItem('last_chapter_index', idx);
    localStorage.setItem('last_chapter_title', chapters[idx].title);
  }
}

export function refreshSyllabusUI() {
  const subject = normaliseSubject(getCurrentSubject());
  const chapters = getChapters();
  const sidebar = document.querySelector('.chapter-list');

  // Update study panel header
  const panelHeader = document.querySelector('.chapters-panel h3');
  if (panelHeader) panelHeader.textContent = `${subject} — Study Materials`;

  if (sidebar) {
    sidebar.innerHTML = chapters.map((ch, i) => `
      <div class="chapter-item ${i < currentIdx ? 'done' : i === currentIdx ? 'active-ch' : ''}" onclick="loadChapter(${i})">
        <div class="ch-num">${i + 1}</div>
        <div class="ch-info">
          <p class="ch-title">${ch.title}</p>
          <p class="ch-meta">${ch.body.replace(/<[^>]*>/g, '').substring(0, 40)}...</p>
        </div>
        <div class="ch-status"></div>
      </div>
    `).join('');
  }

  // Also refresh the Syllabus Grid
  const grid = document.getElementById('syllabus-grid');
  if (grid) {
    const modules = getModules();
    grid.innerHTML = modules.map(m => `
      <div class="unit-card ${m.class}">
        <div class="unit-badge ${m.class === 'active-unit' ? 'current' : ''}">${m.icon}</div>
        <div class="unit-num">${m.num}</div>
        <h3>${m.title}</h3>
        <p>${m.desc}</p>
        <div class="unit-progress"><div class="unit-bar" style="width: ${m.progress}%"></div></div>
        <span class="unit-status ${m.class === 'locked' ? 'locked-s' : m.progress === 100 ? 'done' : 'progress'}">${m.status}</span>
      </div>
    `).join('');
  }
}

export function prevChapter() {
  if (currentIdx > 0) loadChapter(currentIdx - 1);
}

export function nextChapter() {
  const chapters = getChapters();
  if (currentIdx < chapters.length - 1) loadChapter(currentIdx + 1);
}
